# Zensical configuration file

[project]
site_name = "Notes"
site_description = "My Learning Note Repository"
site_author = "Eurekaimer"
site_url = "https://www.eurekaimer.icu/notes"
repo_url = "https://github.com/Eurekaimer/notes"

copyright = """
Copyright &copy; 2024-2026 Eurekaimer
"""

edit_uri = "https://github.com/Eurekaimer/notes/edit/main/docs/"

nav = [
    { "Home" = "index.md" },
    { "Analysis" = [
        "Analysis/index.md",
        { "Mathematical Analysis" = [
            "Analysis/MathematicalAnalysis/index.md",
            { "Preliminaries" = "Analysis/MathematicalAnalysis/预备知识(数学分析).md" },
            { "Textbook Answers" = [
                "Analysis/MathematicalAnalysis/Answers/index.md",
                { "多元函数的极限与连续" = "Analysis/MathematicalAnalysis/Answers/多元函数的极限与连续.md" },
            ]},
            { "Monthly Exams" = "Analysis/MathematicalAnalysis/MonthlyExams/index.md" },
        ]},
        { "Real Analysis" = [
            "Analysis/RealAnalysis/index.md",
            { "第1章 集合与实数集" = "Analysis/RealAnalysis/第1章 集合与实数集.md" },
            { "周性伟 Ch1" = "Analysis/RealAnalysis/周性伟-Ch1.md" },
            { "周性伟 Ch2" = "Analysis/RealAnalysis/周性伟-Ch2.md" },
        ]},
        { "Functional Analysis" = [
            "Analysis/FunctionalAnalysis/index.md",
            { "Preliminaries" = "Analysis/FunctionalAnalysis/Functional_Analysis-Preliminaries(Lecture).md" },
            { "Banach Spaces" = "Analysis/FunctionalAnalysis/Banach Spaces.md" },
            { "Hilbert Spaces" = "Analysis/FunctionalAnalysis/Hilbert Spaces.md" },
            { "Continuous Linear Operators" = "Analysis/FunctionalAnalysis/Continuous linear operators.md" },
            { "Some Big Theorems" = "Analysis/FunctionalAnalysis/Some big theorems.md" },
            { "2020-2021 Final" = "Analysis/FunctionalAnalysis/泛函分析2020-2021期末.md" },
            { "2021-2022 Final" = "Analysis/FunctionalAnalysis/泛函分析2021-2022期末.md" },
            { "2023-2024 Final" = "Analysis/FunctionalAnalysis/泛函分析2023-2024期末.md" },
        ]},
        { "Reading Notes" = [
            "Analysis/ReadingNotes/index.md",
            { "Principles of Mathematical Analysis (Rudin)" = [
                { "The Real and Complex Number Systems" = "Analysis/ReadingNotes/Principles of Mathematical Analysis(Rudin)/The Real and Complex Number Systems.md" },
            ]},
        ]},
    ]},
    { "Algebra" = [
        "Algebra/index.md",
        { "Advanced Algebra" = [
            "Algebra/AdvancedAlgebra/index.md",
            { "二次型" = "Algebra/AdvancedAlgebra/二次型.md" },
        ]},
    ]},
    { "Probability" = [
        "Probability/index.md",
        { "Elementary Probability" = [
            "Probability/ElementaryProbability/index.md",
            { "Combinatorial Analysis" = "Probability/ElementaryProbability/Combinatorial Analysis.md" },
            { "Sets, Axioms of Probability" = "Probability/ElementaryProbability/Sets, Axioms of Probability.md" },
        ]},
        { "Stochastic Process" = [
            "Probability/StochasticProcess/index.md",
            { "Poisson Processes" = "Probability/StochasticProcess/PoissonProcesses.md" },
            { "Lecture 1 - Introduction & Preliminaries" = "Probability/StochasticProcess/Assets/Lecture 1 - Introduction & Preliminaries.md" },
            { "Lecture 2 - Poisson Processes" = "Probability/StochasticProcess/Assets/Lecture 2 - Poisson Processes.md" },
            { "Lecture 3 - Extensions of Poisson Process" = "Probability/StochasticProcess/Assets/Lecture 3 - Extensions of Poisson Process.md" },
            { "Lecture 4 - Discrete-time Markov Chains" = "Probability/StochasticProcess/Assets/Lecture 4 - Discrete-time Markov Chains.md" },
            { "Lecture 5 - Classification of States" = "Probability/StochasticProcess/Assets/Lecture 5 - Classification of States.md" },
            { "Lecture 6 - Limit Behaviour & Ergodic Theory" = "Probability/StochasticProcess/Assets/Lecture 6 - Limit Behaviour & Ergodic Theory.md" },
        ]},
    ]},
    { "Statistics" = [
        "Statistics/index.md",
        { "Mathematical Statistics" = [
            "Statistics/MathematicalStatistics/index.md",
            { "基本概念" = "Statistics/MathematicalStatistics/Assets/基本概念.md" },
            { "点估计" = "Statistics/MathematicalStatistics/Assets/点估计.md" },
            { "假设检验——显著性检验" = "Statistics/MathematicalStatistics/Assets/假设检验——显著性检验.md" },
            { "25 数理统计期中" = "Statistics/MathematicalStatistics/Assets/25数理统计期中.md" },
        ]},
        { "Regression Analysis" = [
            "Statistics/RegressionAnalysis/index.md",
            { "第一章 引论（王松桂）" = "Statistics/RegressionAnalysis/第一章-引论-王松桂.md" },
        ]},
        { "Operations Research" = [
            "Statistics/OperationsResearch/index.md",
            { "线性规划与目标规划" = "Statistics/OperationsResearch/线性规划与目标规划.md" },
            { "无约束问题" = "Statistics/OperationsResearch/无约束问题.md" },
        ]},
        { "STAT260" = "Statistics/STAT260/index.md" },
    ]},
    { "Computer Science" = [
        "CS/index.md",
        { "CS50x" = [
            "CS/CS50x/index.md",
            { "Week 0 Scratch" = "CS/CS50x/Week 0 Scratch.md" },
            { "Week 1 C" = "CS/CS50x/Week 1 C.md" },
            { "Week 2 Arrays" = "CS/CS50x/Week 2 Arrays.md" },
        ]},
        { "CS61A" = [
            "CS/CS61A/index.md",
            { "Project 1 - The Game of Hog" = "CS/CS61A/Project 1-The Game of Hog.md" },
            { "Project 2 - Autocorrected Typing Software" = "CS/CS61A/Project 2-CS 61A Autocorrected Typing Software.md" },
            { "Week 1" = "CS/CS61A/Week 1.md" },
            { "Week 2" = "CS/CS61A/Week 2.md" },
            { "Week 3" = "CS/CS61A/Week 3.md" },
            { "Week 4" = "CS/CS61A/Week 4.md" },
            { "Week 5" = "CS/CS61A/Week 5.md" },
            { "Week 6" = "CS/CS61A/Week 6.md" },
            { "Week 7" = "CS/CS61A/Week 7.md" },
        ]},
        { "CS231n" = [
            "CS/CS231n/CS231n.md",
            { "Lecture 1 - Introduction" = "CS/CS231n/CS231n-Lecture1 Introduction.md" },
        ]},
    ]},
    { "Tech" = [
        "Tech/index.md",
        { "Wheels" = [
            { "Overview" = "Tech/Wheels/轮子大家族.md" },
            { "LaTeX (VSCode)" = "Tech/Wheels/LaTeX(VScode).md" },
            { "Mermaid" = "Tech/Wheels/Mermaid Note.md" },
            { "Sioyek" = "Tech/Wheels/Sioyek.md" },
            { "PicGo" = "Tech/Wheels/图床搭建(PicGo).md" },
            { "Stata 18" = "Tech/Wheels/Stata18安装.md" },
            { "Python Environment" = "Tech/Wheels/Python环境安装和配置.md" },
            { "Python Projects" = "Tech/Wheels/Python的项目管理.md" },
            { "Rust" = "Tech/Wheels/Rust环境安装.md" },
            { "CachyOS Recovery" = "Tech/Wheels/CachyOS-Recovery.md" },
            { "CachyOS YYS" = "Tech/Wheels/CachyOS-YYS.md" },
            { "NixOS Arknights" = "Tech/Wheels/如何使用NixOS玩明日方舟.md" },
        ]},
    ]},
    { "WebSource" = [
        "WebSource/index.md",
        { "CS Resources" = "WebSource/计算机科学(CS)资源汇总.md" },
        { "Math & Statistics Resources" = "WebSource/数学(统计学)资源汇总.md" },
        { "Wandering" = "WebSource/wandering.md" },
        { "Video Archive" = "WebSource/videos/index.md" },
    ]},
    { "Research" = "Research/index.md" },
    { "Physics" = [
        { "University Physics 2" = [
            "Physics/UniversityPhysics2/index.md",
            { "真空中的静电场" = "Physics/UniversityPhysics2/大学物理2-1-真空中的静电场.md" },
            { "静电场中的导体和电介质" = "Physics/UniversityPhysics2/大学物理2-2-静电场中的导体和电介质.md" },
            { "直流电和交流电" = "Physics/UniversityPhysics2/大学物理2-3-直流电和交流电.md" },
            { "恒定磁场" = "Physics/UniversityPhysics2/大学物理2-4-恒定磁场.md" },
            { "电磁感应" = "Physics/UniversityPhysics2/大学物理2-5-电磁感应.md" },
        ]},
    ]},
    { "Friends Link" = "friends-link.md" },
]


extra_css = [
    "stylesheets/extra.css",
    "stylesheets/key.css",
    "stylesheets/mouse-color.css",
    "stylesheets/videos.css",
    "https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css",  # 霞鹜文楷
]

extra_javascript = [
    "javascripts/mathjax.js",
    "javascripts/typewriter.js",
    "javascripts/videos.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js",
    "javascripts/mermaid.mjs"
]

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

# Admonitions and details
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]

# Mermaid
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

# Grids
[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]

# Task Lists
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

# toc link
[project.markdown_extensions.toc]
permalink = "⚓︎"
toc_depth = 3

# footnote
[project.markdown_extensions.footnotes]

[project.theme]
variant = "modern"
custom_dir = "overrides"
favicon = "images/xiaoju.jpg"
language = "zh"

features = [
    "announce.dismiss",
    "content.action.edit",
    "content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
    # "toc.integrate", # 子目录进入右侧
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.theme.font]
text = "LXGW WenKai"  
code = "Roboto Mono" 

[project.theme.icon]
logo = "lucide/pi"
repo = "fontawesome/brands/github"

[project.theme.icon.admonition]
note = "fontawesome/solid/note-sticky"
abstract = "fontawesome/solid/book"
info = "fontawesome/solid/circle-info"
tip = "fontawesome/solid/bullhorn"
success = "fontawesome/solid/check"
question = "fontawesome/solid/circle-question"
warning = "fontawesome/solid/triangle-exclamation"
failure = "fontawesome/solid/bomb"
danger = "fontawesome/solid/skull"
bug = "fontawesome/solid/robot"
example = "fontawesome/solid/flask"
quote = "fontawesome/solid/quote-left"
tldr = "fontawesome/solid/cube"

# ----------------------------------------------------------------------------
# The "extra" section contains miscellaneous settings. material/mdi/wechat
# ----------------------------------------------------------------------------
[project.markdown_extensions.pymdownx.emoji]

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/Eurekaimer"
name = "GitHub"

[[project.extra.social]]
icon = "fontawesome/brands/qq"
link = "https://raw.githubusercontent.com/Eurekaimer/MyIMGs/refs/heads/main/img/QQ.png" 
name = "QQ"

[[project.extra.social]]
icon = "simple/wechat"
link = "https://raw.githubusercontent.com/Eurekaimer/MyIMGs/refs/heads/main/img/Wechat.jpg" 
name = "WeChat"

[[project.extra.social]]
icon = "fontawesome/brands/bilibili"
link = "https://space.bilibili.com/702046230?spm_id_from=333.1007.0.0" 
name = "Bilibili"

[[project.extra.social]]
icon = "fontawesome/solid/paper-plane"
link = "mailto:<2507983039@qq.com>" 
name = "Email 2507983039@qq.com"