# Zensical configuration file

[project]
site_name = "Eurekaimer's Digital Garden"
site_description = "My Learning Note Repository"
site_author = "Eurekaimer"
site_url = "https://www.eurekaimer.icu/Stathelper"
repo_url = "https://github.com/Eurekaimer/Stathelper"

copyright = """
Copyright &copy; 2024-2026 Eurekaimer
"""

edit_uri = "https://github.com/Eurekaimer/Stathelper/edit/main/docs/"

nav = [
   { "Stathelper" = "index.md" },
   { "HDP" = [
        "HDP/index.md",
        { "Chapter 1" = "HDP/Chapter-1.md" },
        ]},
    { "STAT260" = [
        "STAT260/index.md",
        { "Chapter 1" = "STAT260/Chapter-1.md" },
        ]},
    { "CS" = [
        { "CS Learning" = "CS/index.md" },
        { "Deep Learning" = [
            { "Deep Learning" = "CS/DL/index.md" },
            { "CS231n" = "CS/CS231n/CS231n.md" },
        ]},
        { "CS Introduction" = [
            {"DL" = "CS/DL/index.md"},
            {"CS61A" = "CS/CS61A/index.md"},
        ]},
    ]},
    { "Analysis" = [
        "Analysis/index.md",
        { "Mathematical Analysis" = [
            { "南开大学数学分析课本答案" = [
                "Analysis/南开大学数学分析答案/index.md",
                { "多元函数的极限与连续" = "Analysis/南开大学数学分析答案/多元函数的极限与连续.md"},
            ]},
            { "Lecture Notes" = [
                "Analysis/数学分析(Lecture Notes)/index.md",
                { "多元函数的极限与连续" = "Analysis/数学分析(Lecture Notes)/预备知识(数学分析).md"},
            ]},
        ]},
    ]},
    { "Probability" = [
        "Probability/index.md",
        { "Stochastic Process" = [
            "Probability/Stochastic_Process/index.md",
            { "Lecture 2" = "Probability/Stochastic_Process/Poisson_Processes.md"},
        ]},
    ]},
    { "Boring" = [
        { "大学物理2" = [
            "Boring/大学物理2/index.md",
            { "真空中的静电场" = "Boring/大学物理2/大学物理2-1-真空中的静电场.md" },
            { "静电场中的导体和电介质" = "Boring/大学物理2/大学物理2-2-静电场中的导体和电介质.md" },
            { "直流电和交流电" = "Boring/大学物理2/大学物理2-3-直流电和交流电.md" },
            { "恒定磁场" = "Boring/大学物理2/大学物理2-4-恒定磁场.md" },
            { "电磁感应" = "Boring/大学物理2/大学物理2-5-电磁感应.md" },
        ]},
    ]},
    { "ACGN" = [
        { "Anime Rank" = "ACGN/Anime.md"},
        { "Yuri Rank" = "ACGN/Yuri.md"},
        { "Yuri Novel" = "ACGN/百合文盘点.md"},
        { "Galgame" = [
            "Galgame/index.md",
            { "仅你一人" = "Galgame/only-you.md"},
            { "Flowers Spring" = "Galgame/only-you.md"},
        ]},
        ]},
    { "Tech" = [
        "Tech/index.md",
        { "Wheels" = [
            { "轮子大家族" = "Tech/Wheels/轮子大家族.md"},
            { "LaTeX" = "Tech/Wheels/LaTeX(VScode).md"},
            { "Sioyek" = "Tech/Wheels/Sioyek.md"},
            { "CachyOS-Recovery" = "Tech/Wheels/CachyOS-Recovery.md"},
            { "Mermaid" = "Tech/Wheels/Mermaid Note.md"},
            { "图床搭建(PicGo)" = "Tech/Wheels/图床搭建(PicGo).md"},
            { "Stata18安装" = "Tech/Wheels/Stata18安装.md"},
            { "Python环境安装和配置" = "Tech/Wheels/Python环境安装和配置.md"},
            { "Python的项目管理" = "Tech/Wheels/Python的项目管理.md"},
            { "Rust环境安装" = "Tech/Wheels/Rust环境安装.md"},
            { "如何使用NixOS玩明日方舟" = "Tech/Wheels/如何使用NixOS玩明日方舟.md"},
            { "CachyOS-YYS" = "Tech/Wheels/CachyOS-YYS.md"},
        ]},
    ]},
    { "WebSource" = [
        "WebSource/index.md",
        { "Source Websites" = [
            { "Computer Science" = "WebSource/计算机科学(CS)资源汇总.md"},
            { "Math and Statistics" = "WebSource/数学(统计学)资源汇总.md"},
        ]},
        { "克林索尔的最后夏天" = "WebSource/克林索尔的最后夏天.md" },
        { "Video Archive" = "WebSource/videos/index.md" },
        ]},
    { "Friends Link" = "friends-link.md" },
]


extra_css = [
    "stylesheets/extra.css",
    "stylesheets/anime-grid.css",
    "stylesheets/key.css",
    "stylesheets/mouse-color.css",
    "stylesheets/videos.css",
    "https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css",  # 霞鹜文楷
]

extra_javascript = [
    "javascripts/mathjax.js",
    "javascripts/videos.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js",
    "javascripts/mermaid.mjs"
]

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

# Admonitions and details
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]

# Mermaid
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

# Grids
[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]

# Task Lists
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

# toc link
[project.markdown_extensions.toc]
permalink = "⚓︎"
toc_depth = 3

# footnote
[project.markdown_extensions.footnotes]

[project.theme]
variant = "modern"
custom_dir = "overrides"
favicon = "images/xiaoju.jpg"
language = "zh"

features = [
    "announce.dismiss",
    "content.action.edit",
    "content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
    # "toc.integrate", # 子目录进入右侧
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.theme.font]
text = "LXGW WenKai"  
code = "Roboto Mono" 

[project.theme.icon]
logo = "lucide/pi"
repo = "fontawesome/brands/github"

[project.theme.icon.admonition]
note = "fontawesome/solid/note-sticky"
abstract = "fontawesome/solid/book"
info = "fontawesome/solid/circle-info"
tip = "fontawesome/solid/bullhorn"
success = "fontawesome/solid/check"
question = "fontawesome/solid/circle-question"
warning = "fontawesome/solid/triangle-exclamation"
failure = "fontawesome/solid/bomb"
danger = "fontawesome/solid/skull"
bug = "fontawesome/solid/robot"
example = "fontawesome/solid/flask"
quote = "fontawesome/solid/quote-left"
tldr = "fontawesome/solid/cube"

# ----------------------------------------------------------------------------
# The "extra" section contains miscellaneous settings. material/mdi/wechat
# ----------------------------------------------------------------------------
[project.markdown_extensions.pymdownx.emoji]

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/Eurekaimer"
name = "GitHub"

[[project.extra.social]]
icon = "fontawesome/brands/qq"
link = "https://raw.githubusercontent.com/Eurekaimer/MyIMGs/refs/heads/main/img/QQ.png" 
name = "QQ"

[[project.extra.social]]
icon = "simple/wechat"
link = "https://raw.githubusercontent.com/Eurekaimer/MyIMGs/refs/heads/main/img/Wechat.jpg" 
name = "WeChat"

[[project.extra.social]]
icon = "fontawesome/brands/bilibili"
link = "https://space.bilibili.com/702046230?spm_id_from=333.1007.0.0" 
name = "Bilibili"

[[project.extra.social]]
icon = "fontawesome/solid/paper-plane"
link = "mailto:<2507983039@qq.com>" 
name = "Email 2507983039@qq.com"